@echo off
REM ── MutualFundsRadar Daily Scraper ──────────────────────────────
REM Auto-generated by setup_automation.py
REM Task: MutualFundsRadar_Daily

cd /d "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index"

echo. >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log"
echo ================================================================== >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log"
echo [%date% %time%] Starting daily scrape >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log"
echo ================================================================== >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log"

"C:\Users\Hadi-Alghanim\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe" "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\funds_scraper.py" --no-playwright >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log" 2>&1

echo [%date% %time%] Scrape finished (exit code: %ERRORLEVEL%) >> "C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index\scraper_auto.log"
