"""
setup_automation.py — Register a daily Windows Scheduled Task for funds_scraper.py.

Creates:
  1. daily_update.bat  — launcher script (cd + python funds_scraper.py)
  2. Windows Task      — "MutualFundsRadar_Daily" via schtasks.exe

The task runs every day at 13:00 (1 PM), which is after Saudi market
closes (12:00 local) — giving Tadawul time to publish updated NAVs.

Usage:
    python setup_automation.py              # create task at 13:00
    python setup_automation.py --time 14:30 # custom time
    python setup_automation.py --remove     # delete the task

NOTE: Creating a scheduled task requires an elevated (Administrator)
      command prompt.  The script will detect and warn if not elevated.
"""

import argparse
import ctypes
import os
import subprocess
import sys


# ── Constants ────────────────────────────────────────────────────────────────
TASK_NAME = "MutualFundsRadar_Daily"
BAT_NAME = "daily_update.bat"
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
BAT_PATH = os.path.join(PROJECT_DIR, BAT_NAME)
SCRAPER_SCRIPT = "funds_scraper.py"


def is_admin() -> bool:
    """Check if the current process has Administrator privileges."""
    try:
        return ctypes.windll.shell32.IsUserAnAdmin() != 0
    except AttributeError:
        # Not on Windows
        return False


def find_python() -> str:
    """Return the absolute path to the current Python interpreter."""
    return sys.executable


def create_bat_file() -> str:
    """
    Create (or overwrite) daily_update.bat in the project directory.

    The bat file:
      1. Turns off command echo
      2. Changes directory to the project folder
      3. Runs funds_scraper.py with --no-playwright (pure curl_cffi)
      4. Appends output to a log file with a timestamp
    """
    python_path = find_python()
    scraper_path = os.path.join(PROJECT_DIR, SCRAPER_SCRIPT)
    log_path = os.path.join(PROJECT_DIR, "scraper_auto.log")

    bat_content = f"""@echo off
REM ── MutualFundsRadar Daily Scraper ──────────────────────────────
REM Auto-generated by setup_automation.py
REM Task: {TASK_NAME}

cd /d "{PROJECT_DIR}"

echo. >> "{log_path}"
echo ================================================================== >> "{log_path}"
echo [%date% %time%] Starting daily scrape >> "{log_path}"
echo ================================================================== >> "{log_path}"

"{python_path}" "{scraper_path}" --no-playwright >> "{log_path}" 2>&1

echo [%date% %time%] Scrape finished (exit code: %ERRORLEVEL%) >> "{log_path}"
"""

    with open(BAT_PATH, "w", encoding="utf-8") as f:
        f.write(bat_content)

    print(f"  [1/2] Created: {BAT_PATH}")
    print(f"         Python : {python_path}")
    print(f"         Script : {scraper_path}")
    print(f"         Log    : {log_path}")
    return BAT_PATH


def create_scheduled_task(run_time: str) -> bool:
    """
    Register a Windows Scheduled Task using schtasks.exe.

    Args:
        run_time: HH:MM format (24-hour), e.g. "13:00"

    Returns:
        True if task was created successfully, False otherwise.
    """
    cmd = [
        "schtasks.exe",
        "/Create",
        "/TN", TASK_NAME,
        "/TR", f'"{BAT_PATH}"',
        "/SC", "DAILY",
        "/ST", run_time,
        "/F",               # /F = force overwrite if task already exists
        "/RL", "HIGHEST",   # Run with highest privileges
    ]

    print(f"  [2/2] Registering task: {TASK_NAME}")
    print(f"         Schedule : Daily at {run_time}")
    print(f"         Command  : {' '.join(cmd)}")
    print()

    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except FileNotFoundError:
        print("  ERROR: schtasks.exe not found. Are you on Windows?")
        return False
    except subprocess.TimeoutExpired:
        print("  ERROR: schtasks command timed out.")
        return False

    if result.returncode == 0:
        print(f"  SUCCESS: Task '{TASK_NAME}' created.")
        if result.stdout.strip():
            print(f"  schtasks: {result.stdout.strip()}")
        return True
    else:
        print(f"  FAILED: schtasks returned exit code {result.returncode}")
        if result.stderr.strip():
            print(f"  stderr: {result.stderr.strip()}")
        if result.stdout.strip():
            print(f"  stdout: {result.stdout.strip()}")

        if "Access is denied" in (result.stderr + result.stdout):
            print()
            print("  HINT: Run this script from an Administrator command prompt:")
            print("        Right-click Command Prompt -> Run as administrator")
        return False


def remove_scheduled_task() -> bool:
    """Delete the scheduled task from Windows Task Scheduler."""
    cmd = ["schtasks.exe", "/Delete", "/TN", TASK_NAME, "/F"]

    print(f"Removing task: {TASK_NAME}")
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    except FileNotFoundError:
        print("  ERROR: schtasks.exe not found.")
        return False

    if result.returncode == 0:
        print(f"  SUCCESS: Task '{TASK_NAME}' removed.")
        # Clean up bat file
        if os.path.isfile(BAT_PATH):
            os.remove(BAT_PATH)
            print(f"  Deleted: {BAT_PATH}")
        return True
    else:
        stderr = result.stderr.strip() + result.stdout.strip()
        print(f"  FAILED: {stderr}")
        return False


def query_task() -> None:
    """Show the current status of the scheduled task."""
    cmd = ["schtasks.exe", "/Query", "/TN", TASK_NAME, "/V", "/FO", "LIST"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
        if result.returncode == 0:
            print(result.stdout)
        else:
            print(f"  Task '{TASK_NAME}' not found in Task Scheduler.")
    except FileNotFoundError:
        print("  ERROR: schtasks.exe not found.")


def main():
    parser = argparse.ArgumentParser(
        description="Set up daily Windows scheduled task for funds_scraper.py",
    )
    parser.add_argument(
        "--time", default="13:00",
        help="Daily run time in HH:MM 24-hour format (default: 13:00)",
    )
    parser.add_argument(
        "--remove", action="store_true",
        help="Remove the scheduled task instead of creating it",
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Show current task status and exit",
    )
    args = parser.parse_args()

    print("=" * 60)
    print("  MutualFundsRadar — Automation Setup")
    print("=" * 60)
    print(f"  Project dir : {PROJECT_DIR}")
    print(f"  Platform    : {sys.platform}")
    print(f"  Admin       : {'Yes' if is_admin() else 'No'}")
    print()

    # ── Status query ─────────────────────────────────────────────────
    if args.status:
        query_task()
        return

    # ── Remove mode ──────────────────────────────────────────────────
    if args.remove:
        ok = remove_scheduled_task()
        sys.exit(0 if ok else 1)

    # ── Validate platform ────────────────────────────────────────────
    if sys.platform != "win32":
        print("  ERROR: This script only works on Windows.")
        print("  For Linux/macOS, use cron:")
        print(f"    0 13 * * * cd {PROJECT_DIR} && python {SCRAPER_SCRIPT}")
        sys.exit(1)

    # ── Validate time format ─────────────────────────────────────────
    try:
        parts = args.time.split(":")
        assert len(parts) == 2
        h, m = int(parts[0]), int(parts[1])
        assert 0 <= h <= 23 and 0 <= m <= 59
    except (ValueError, AssertionError):
        print(f"  ERROR: Invalid time format '{args.time}'. Use HH:MM (e.g., 13:00)")
        sys.exit(1)

    # ── Admin check ──────────────────────────────────────────────────
    if not is_admin():
        print("  WARNING: Not running as Administrator.")
        print("  schtasks may fail. Right-click Command Prompt -> Run as administrator.")
        print()

    # ── Validate scraper exists ──────────────────────────────────────
    scraper_full = os.path.join(PROJECT_DIR, SCRAPER_SCRIPT)
    if not os.path.isfile(scraper_full):
        print(f"  ERROR: {SCRAPER_SCRIPT} not found at {scraper_full}")
        sys.exit(1)

    # ── Step 1: Create bat file ──────────────────────────────────────
    create_bat_file()
    print()

    # ── Step 2: Register scheduled task ──────────────────────────────
    ok = create_scheduled_task(args.time)
    print()

    if ok:
        print("-" * 60)
        print("  Setup complete! The scraper will run daily at", args.time)
        print()
        print("  Useful commands:")
        print(f"    python setup_automation.py --status     # check task status")
        print(f"    python setup_automation.py --remove     # delete the task")
        print(f"    python setup_automation.py --time 14:30 # change schedule")
        print("-" * 60)
    else:
        sys.exit(1)


if __name__ == "__main__":
    main()
