# ════════════════════════════════════════════════════════════════════════
#  setup_scraper_automation.ps1
#  ----------------------------------------------------------------------
#  ONE-shot installer for the Foreign Liquidity scraper schedule.
#
#  Does FOUR things in order:
#    1. Auto-elevates to Administrator if not already running as admin.
#    2. Writes run_scraper_logged.bat (with full diagnostic logging) into
#       the project folder, overwriting any existing copy.
#    3. Removes any pre-existing scheduled task whose name starts with
#       "Foreign Liquidity Scraper" (cleans up old/duplicate registrations).
#    4. Registers a new task "Foreign Liquidity Scraper - Daily" that runs
#       run_scraper_logged.bat every day at 14:00 (2:00 PM).
#
#  HOW TO RUN (one click):
#     Right-click this file in Explorer → "Run with PowerShell".
#     A UAC prompt will appear; click "Yes". The script handles the rest.
#
#  HOW TO RUN (one command, from PowerShell):
#     powershell -ExecutionPolicy Bypass -File ".\setup_scraper_automation.ps1"
#
#  Safe to re-run any number of times — it cleans up after itself.
# ════════════════════════════════════════════════════════════════════════

$ErrorActionPreference = 'Stop'

# ─── Config ─────────────────────────────────────────────────────────────
$WorkingDir = 'C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index'
$ScriptName = 'foreign_liquidity_scraper.py'
$RunnerBat  = 'run_scraper_logged.bat'
$LogFile    = 'scraper_log.txt'
$TaskName   = 'Foreign Liquidity Scraper - Daily'
$RunTime    = '14:00'

# ─── 1. Auto-elevate to Administrator ───────────────────────────────────
# Register-ScheduledTask for arbitrary task names usually requires admin.
# If we're not elevated, relaunch ourselves with -Verb RunAs and exit.
$currentIdentity = [Security.Principal.WindowsIdentity]::GetCurrent()
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal($currentIdentity)
$isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if (-not $isAdmin) {
    Write-Host ''
    Write-Host 'Not running as Administrator. Relaunching with elevation...' -ForegroundColor Yellow
    $args = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', "`"$PSCommandPath`""
    )
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $args
    exit
}

Write-Host ''
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host '  Foreign Liquidity Scraper - Automated Schedule Installer' -ForegroundColor Cyan
Write-Host '================================================================' -ForegroundColor Cyan
Write-Host ''

# ─── 2. Verify project folder + Python script exist ─────────────────────
if (-not (Test-Path -LiteralPath $WorkingDir)) {
    Write-Host ('ERROR: Project folder not found: {0}' -f $WorkingDir) -ForegroundColor Red
    Read-Host 'Press Enter to close'
    exit 1
}

$ScriptPath = Join-Path $WorkingDir $ScriptName
if (-not (Test-Path -LiteralPath $ScriptPath)) {
    Write-Host ('ERROR: Python scraper not found: {0}' -f $ScriptPath) -ForegroundColor Red
    Read-Host 'Press Enter to close'
    exit 1
}

Write-Host ('Project folder : {0}' -f $WorkingDir) -ForegroundColor Gray
Write-Host ('Python script  : {0}' -f $ScriptName) -ForegroundColor Gray

# Friendly pre-flight: confirm `py` or `python` exists for the current user.
# (The .bat tries `py` first, then `python`, so either is fine.)
$pyExe = $null
if (Get-Command py     -ErrorAction SilentlyContinue) { $pyExe = 'py' }
elseif (Get-Command python -ErrorAction SilentlyContinue) { $pyExe = 'python' }
if ($pyExe) {
    Write-Host ('Python launcher: {0} ({1})' -f $pyExe, (Get-Command $pyExe).Source) -ForegroundColor Gray
} else {
    Write-Host 'WARNING: neither "py" nor "python" found on PATH for current user.' -ForegroundColor Yellow
    Write-Host '         The task will fail at run time. Install Python or fix PATH first.' -ForegroundColor Yellow
}

Write-Host ''

# ─── 3. Generate run_scraper_logged.bat ─────────────────────────────────
# Single-quoted here-string so PowerShell does NOT try to expand the `%var%`
# tokens inside the .bat. Closing '@ MUST be at column 0.
$batContent = @'
@echo off
REM ====================================================================
REM  run_scraper_logged.bat
REM  Auto-generated by setup_scraper_automation.ps1 - do not hand-edit.
REM
REM  Robust Task Scheduler wrapper. Logs every step, every error, and
REM  every Python traceback to scraper_log.txt so silent failures become
REM  visible failures.
REM ====================================================================

setlocal EnableDelayedExpansion

set "WORK_DIR=C:\Users\Hadi-Alghanim\Desktop\New folder\inflation_index"
set "SCRIPT=foreign_liquidity_scraper.py"
set "LOG=%WORK_DIR%\scraper_log.txt"

REM Force UTF-8 console + unbuffered Python output.
chcp 65001 >nul 2>&1
set "PYTHONIOENCODING=utf-8"
set "PYTHONUNBUFFERED=1"

REM Lock to absolute project folder. Task Scheduler's CWD is unreliable.
pushd "%WORK_DIR%" 2>nul
if errorlevel 1 (
    echo [%date% %time%] FATAL: working directory not found: %WORK_DIR% >> "%LOG%"
    exit /b 2
)

REM Auto-rotate log if it grows past 5 MB so it doesn't bloat forever.
for %%A in ("%LOG%") do set "LOG_SIZE=%%~zA"
if defined LOG_SIZE if !LOG_SIZE! GEQ 5242880 (
    if exist "%LOG%.old" del "%LOG%.old" >nul 2>&1
    ren "%LOG%" "scraper_log.txt.old" >nul 2>&1
)

echo. >> "%LOG%"
echo ============================================================ >> "%LOG%"
echo [%date% %time%] BEGIN scheduled run >> "%LOG%"
echo ============================================================ >> "%LOG%"
echo Working directory : %CD% >> "%LOG%"
echo Script            : %SCRIPT% >> "%LOG%"
echo Run as user       : %USERNAME%@%COMPUTERNAME% >> "%LOG%"
echo Session           : %SESSIONNAME% >> "%LOG%"

if not exist "%SCRIPT%" (
    echo [%date% %time%] FATAL: %SCRIPT% not found in %CD% >> "%LOG%"
    popd
    exit /b 3
)

REM Resolve a Python interpreter. Task Scheduler runs without the user's
REM interactive PATH, so "python" may not resolve even when it does in cmd.
REM Try `py` (the official launcher) first, then `python`.
set "PY_EXE="
where py     >nul 2>&1 && set "PY_EXE=py"
if not defined PY_EXE where python >nul 2>&1 && set "PY_EXE=python"

REM If neither launcher resolved, hard-code your interpreter here.
REM Find it via `where python` in a normal cmd prompt and paste below.
REM Example:
REM   if not defined PY_EXE set "PY_EXE=C:\Users\Hadi-Alghanim\AppData\Local\Programs\Python\Python313\python.exe"

if not defined PY_EXE (
    echo [%date% %time%] FATAL: no Python interpreter found on PATH. >> "%LOG%"
    echo                       Edit run_scraper_logged.bat and set PY_EXE manually. >> "%LOG%"
    popd
    exit /b 4
)

echo Python launcher   : %PY_EXE% >> "%LOG%"
echo --- Python info --- >> "%LOG%"
%PY_EXE% -c "import sys; print('exe     :', sys.executable); print('version :', sys.version.split()[0]); print('prefix  :', sys.prefix)" >> "%LOG%" 2>&1

echo --- Scraper output --- >> "%LOG%"
%PY_EXE% "%SCRIPT%" >> "%LOG%" 2>&1
set "RC=%ERRORLEVEL%"

echo --- End of run --- >> "%LOG%"
if %RC% EQU 0 (
    echo [%date% %time%] OK: scraper exited cleanly. >> "%LOG%"
) else (
    echo [%date% %time%] FAILED: scraper exited with code %RC%. >> "%LOG%"
    echo                       Scroll up for the traceback. >> "%LOG%"
)

popd
endlocal & exit /b %RC%
'@

$RunnerPath = Join-Path $WorkingDir $RunnerBat

# ASCII encoding is safest for .bat files. cmd.exe cannot parse UTF-16 BOMs.
[System.IO.File]::WriteAllText($RunnerPath, $batContent, [System.Text.Encoding]::ASCII)
Write-Host ('Wrote runner   : {0}' -f $RunnerPath) -ForegroundColor Green

if (-not (Test-Path -LiteralPath $RunnerPath)) {
    Write-Host 'ERROR: failed to create runner .bat' -ForegroundColor Red
    Read-Host 'Press Enter to close'
    exit 1
}

Write-Host ''

# ─── 4. Remove any existing "Foreign Liquidity Scraper*" tasks ──────────
Write-Host 'Searching for existing scheduled tasks...' -ForegroundColor Cyan
$existing = Get-ScheduledTask -TaskName 'Foreign Liquidity Scraper*' -ErrorAction SilentlyContinue
if ($existing) {
    foreach ($t in $existing) {
        Write-Host ('  Removing: {0}' -f $t.TaskName) -ForegroundColor Yellow
        Unregister-ScheduledTask -TaskName $t.TaskName -Confirm:$false
    }
} else {
    Write-Host '  None found.' -ForegroundColor Gray
}
Write-Host ''

# ─── 5. Register the new task ───────────────────────────────────────────
Write-Host 'Registering new scheduled task...' -ForegroundColor Cyan

$action = New-ScheduledTaskAction `
    -Execute $RunnerPath `
    -WorkingDirectory $WorkingDir

$trigger = New-ScheduledTaskTrigger -Daily -At $RunTime

# Run as the current user, only when logged on, no elevation required.
# The scraper doesn't need admin — only the registration does.
$principal = New-ScheduledTaskPrincipal `
    -UserId ('{0}\{1}' -f $env:USERDOMAIN, $env:USERNAME) `
    -LogonType Interactive `
    -RunLevel Limited

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -MultipleInstances IgnoreNew `
    -ExecutionTimeLimit (New-TimeSpan -Hours 2)

Register-ScheduledTask `
    -TaskName    $TaskName `
    -Action      $action `
    -Trigger     $trigger `
    -Principal   $principal `
    -Settings    $settings `
    -Description 'Runs the Tadawul Foreign Liquidity scraper once per day at 14:00. Output -> scraper_log.txt.' | Out-Null

# ─── 6. Verify + summarize ──────────────────────────────────────────────
$task = Get-ScheduledTask -TaskName $TaskName
$info = $task | Get-ScheduledTaskInfo

Write-Host ''
Write-Host '================================================================' -ForegroundColor Green
Write-Host '  SUCCESS - everything is set up.' -ForegroundColor Green
Write-Host '================================================================' -ForegroundColor Green
Write-Host ''
Write-Host ('  Task name    : {0}' -f $task.TaskName)
Write-Host ('  State        : {0}' -f $task.State)
Write-Host ('  Runs daily at: {0}' -f $RunTime)
Write-Host ('  Next run at  : {0}' -f $info.NextRunTime)
Write-Host ('  Runner .bat  : {0}' -f $RunnerPath)
Write-Host ('  Log file     : {0}\{1}' -f $WorkingDir, $LogFile)
Write-Host ''
Write-Host 'Useful commands:' -ForegroundColor Cyan
Write-Host ('  Run it now once : Start-ScheduledTask -TaskName "{0}"' -f $TaskName)
Write-Host ('  Check status    : Get-ScheduledTaskInfo -TaskName "{0}"' -f $TaskName)
Write-Host ('  Tail the log    : Get-Content -Path "{0}\{1}" -Tail 30 -Wait' -f $WorkingDir, $LogFile)
Write-Host ('  Disable         : Disable-ScheduledTask -TaskName "{0}"' -f $TaskName)
Write-Host ('  Remove          : Unregister-ScheduledTask -TaskName "{0}" -Confirm:$false' -f $TaskName)
Write-Host ''
Write-Host 'TIP: Run the task manually right now to confirm it works:' -ForegroundColor Yellow
Write-Host ('     Start-ScheduledTask -TaskName "{0}"' -f $TaskName) -ForegroundColor Yellow
Write-Host ('     Then open: {0}\{1}' -f $WorkingDir, $LogFile) -ForegroundColor Yellow
Write-Host ''

Read-Host 'Setup complete. Press Enter to close this window'
